# ==============================================================================
# API Dockerfile - DESARROLLO con Yarn y NestJS
# ==============================================================================

# Versión de Node configurable desde docker-compose
ARG NODE_VERSION=20
FROM node:${NODE_VERSION}-alpine

# Instalar dependencias del sistema
RUN apk add --no-cache python3 make g++ bash

WORKDIR /app

# Copiar dependencias
COPY package.json yarn.lock ./
RUN corepack enable


# Copiar código (se sobrescribirá con volumen)
COPY . .
